apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv0
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /srv/nfs/kubedata/vol/0
    server: 192.168.122.1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-mysql-0
  namespace: poc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /srv/nfs/kubedata/vol/1
    server: 192.168.122.1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-mysql-1
  namespace: poc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv2
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /srv/nfs/kubedata/vol/2
    server: 192.168.122.1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-mysql-2
  namespace: poc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
